# Website settings
url: "https://jeanie-oh.github.io"

# Internal nav
nav:
  main:
    blog: "/blog"
    travel: "/travel"
    projects: "/projects"
    app: "/app"
  blog:
    all: "/blog"
    popular: "/blog/popular"
    tags: "/blog/tags"
    rss: "/feed.xml"

# Bio settings
name: "Jeanie Oh"
description: "Blog dedicated to thinking with data, no opinions, just facts."
thumbnail_path: "profile-photos/jeanie-oh-med.jpg"
website_repo_url: "https://github.com/jeanie-oh/jeanie-oh.github.io"
atomic_squirrel_url: "https://www.atomic-squirrel.net/"
gruntwork_url: "https://www.gruntwork.io/"
terraform_up_and_running_url: "https://www.terraformupandrunning.com/"
terraform_up_and_running_code_url: "https://github.com/brikis98/terraform-up-and-running-code"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/jeanie-oh"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/jeanie-oh/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:jeanieoh@berkeley.edu"
    label: "Email"
    value: "jeanieoh@berkeley.edu"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/blog/page:num"
permalink: "/blog/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: jeanie-oh/jeanie-oh.github.io

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
