# Website settings
url: "https://jeanie-oh.github.io"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
    projects: "/projects"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "The Data Chic"
description: "Blog dedicated to thinking with data, no opinions, just facts &quot;Hello, Startup&quot; and &quot;Terraform: Up & Running&quot;, and software engineer at LinkedIn, TripAdvisor, Cisco Systems, and Thomson Financial."
thumbnail_path: "profile-photos/jeanie-oh-medium.jpg"
website_repo_url: "https://github.com/jeanie-oh/jeanie-oh.github.io"
atomic_squirrel_url: "https://www.atomic-squirrel.net/"
gruntwork_url: "https://www.gruntwork.io/"
terraform_up_and_running_url: "https://www.terraformupandrunning.com/"
terraform_up_and_running_code_url: "https://github.com/brikis98/terraform-up-and-running-code"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/jeanie-oh"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/jeanie-oh/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:jeanieoh@berkeley.edu"
    label: "Email"
    value: "jeanieoh@berkeley.edu"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: jeanie-oh/jeanie-oh.github.io

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
